### ISSUE TITLE
LSA+Deberta large - error

### ISSUE THREAD

**Issue by pepi99** [yangheng95/PyABSA#142]
My code is: 
from pyabsa.functional import Trainer
from pyabsa.functional import APCConfigManager
from pyabsa.functional import ABSADatasetList
from pyabsa.functional import APCModelList
import random

seeds = [random.randint(0, 10000) for _ in range(2)]

apc_config_english = APCConfigManager.get_apc_config_english()
apc_config_english.model = APCModelList.FAST_LSA_T
apc_config_english.lcf = 'cdw'
apc_config_english.similarity_threshold = 1
apc_config_english.max_seq_len = 80
apc_config_english.dropout = 0
apc_config_english.cache_dataset = False
apc_config_english.patience = 10
apc_config_english.optimizer = 'radam'
apc_config_english.pretrained_bert = 'microsoft/deberta-v3-large'
apc_config_english.hidden_dim = 1024
apc_config_english.embed_dim = 1024
apc_config_english.num_epoch = 30
apc_config_english.log_step = 50
apc_config_english.learning_rate = 1e-5
apc_config_english.batch_size = 16
apc_config_english.evaluate_begin = 0
apc_config_english.l2reg = 1e-8
apc_config_english.seed = seeds

Laptop14 = ABSADatasetList.Laptop14
Trainer(config=apc_config_english,
        dataset='laptop14',  # train set and test set will be automatically detected
        checkpoint_save_mode=0,  # =None to avoid save model
        auto_device=True  # automatic choose CUDA or CPU
        )

examples = [
    '[ASP]Bitcoin[ASP] to the moon. [ASP]Ethereum[ASP] is bearish.'
]

The error is: 

Traceback (most recent call last):
  File "/Users/petar.ulev/Documents/nlp/PyABSA/demos/aspect_polarity_classification/train_apc_crypto.py", line 35, in <module>
    Trainer(config=apc_config_english,
  File "/Users/petar.ulev/Documents/nlp/PyABSA/pyabsa/functional/trainer/trainer.py", line 135, in __init__
    self.train()
  File "/Users/petar.ulev/Documents/nlp/PyABSA/pyabsa/functional/trainer/trainer.py", line 153, in train
    model = self.model_class(model_arg=self.train_func(self.config, self.from_checkpoint, self.logger))
  File "/Users/petar.ulev/Documents/nlp/PyABSA/pyabsa/utils/pyabsa_utils.py", line 172, in decorated
    return f(*args, **kwargs)
  File "/Users/petar.ulev/Documents/nlp/PyABSA/pyabsa/core/apc/training/apc_trainer.py", line 542, in train4apc
    return trainer.run()
  File "/Users/petar.ulev/Documents/nlp/PyABSA/pyabsa/core/apc/training/apc_trainer.py", line 526, in run
    return self._train(criterion)
  File "/Users/petar.ulev/Documents/nlp/PyABSA/pyabsa/core/apc/training/apc_trainer.py", line 132, in _train
    return self._train_and_evaluate(criterion)
  File "/Users/petar.ulev/Documents/nlp/PyABSA/pyabsa/core/apc/training/apc_trainer.py", line 180, in _train_and_evaluate
    outputs = self.model(inputs)
  File "/Users/petar.ulev/Documents/nlp/PyABSA/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/petar.ulev/Documents/nlp/PyABSA/pyabsa/core/apc/models/ensembler.py", line 144, in forward
    outputs = [self.models[i](inputs) for i in range(len(self.models))]
  File "/Users/petar.ulev/Documents/nlp/PyABSA/pyabsa/core/apc/models/ensembler.py", line 144, in <listcomp>
    outputs = [self.models[i](inputs) for i in range(len(self.models))]
  File "/Users/petar.ulev/Documents/nlp/PyABSA/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/petar.ulev/Documents/nlp/PyABSA/pyabsa/core/apc/models/fast_lsa_t.py", line 43, in forward
    masked_global_context_features = torch.mul(spc_mask_vec, global_context_features)
RuntimeError: The size of tensor a (768) must match the size of tensor b (1024) at non-singleton dimension 2

It also gives the same error with my custom dataset. If I, however, use dataset=ABSADatasetList.Laptop14 in the trainer argument, it gives no error. Why?

**Comment by pepi99** [comment]
Fixed by creating:
#Crypto
CryptoDataset = DatasetItem('crypto', 'crypto')
(in dataset_manager.py)

and then importing it and using it:
Crypto1 = ABSADatasetList.Crypto1

Trainer(config=apc_config_english,
        dataset=Crypto1,  # train set and test set will be automatically detected
        checkpoint_save_mode=0,  # =None to avoid save model
        auto_device=True  # automatic choose CUDA or CPU
        )

My question is still: why is it necessary to create the dataset item instead of passing the string name in the trainer?

**Comment by yangheng95** [comment]
Please clean cache file and retry

**Comment by yangheng95** [comment]
The repo is not a professional project, which is packaged based on my existing research code. Any suggestion is welcome, but I may not have enough time to respond to some advice. In that case, I would like to receive a detailed suggestion for implementation or a direct PR. So I may apply some modifications to meet the scenario as you mentioned in future.

**Comment by pepi99** [comment]
For now, I will use the approach with the Dataset. It works so yea. thanks!
