### ISSUE TITLE
LSA Model does not work with demo extract_aspect.py code

### ISSUE THREAD

**Issue by younghupark** [yangheng95/PyABSA#154]
Attempting to run the [extract_aspects.py](https://github.com/yangheng95/PyABSA/blob/release/demos/aspect_term_extraction/extract_aspects.py) code Getting the following error:

```Traceback (most recent call last):
  File "extract_aspects.py", line 11, in <module>
    auto_device=False  # False means load model on CPU
  File "/Users/younghupark/opt/miniconda3/envs/sent-analysis/lib/python3.7/site-packages/pyabsa/utils/pyabsa_utils.py", line 173, in decorated
    return f(*args, **kwargs)
  File "/Users/younghupark/opt/miniconda3/envs/sent-analysis/lib/python3.7/site-packages/pyabsa/functional/checkpoint/checkpoint_manager.py", line 135, in get_aspect_extractor
    aspect_extractor = AspectExtractor(checkpoint, sentiment_map=sentiment_map, eval_batch_size=eval_batch_size)
  File "/Users/younghupark/opt/miniconda3/envs/sent-analysis/lib/python3.7/site-packages/pyabsa/core/atepc/prediction/aspect_extractor.py", line 95, in __init__
    raise RuntimeError('Exception: {} Fail to load the model from {}! '.format(e, model_arg))
RuntimeError: Exception: 'APCConfigManager' object has no attribute 'num_labels' Fail to load the model from checkpoints/ATEPC_ENGLISH_CHECKPOINT/fast_lsa_t_acc_84.84_f1_82.36! 
```

**Comment by yangheng95** [comment]
LSA is not available for ATEPC, please be sure that ATEPC and APC are different.

**Comment by younghupark** [comment]
Is there a means to just perform ATE as well then?

**Comment by yangheng95** [comment]
If you need to do ATE only, you can set predict_sentiment=False
