### ISSUE TITLE
测试rain_apc_bert_baseline.py 遇到loss=nan和加载的错误

### ISSUE THREAD

**Issue by hk975** [yangheng95/PyABSA#159]
你好， 感谢您的工作！ 我在测试 demos/aspect_polarity_classification/bert-baselines/train_apc_bert_baseline.py 文件会报错
运行Laptop14没有问题， 但是在运行到restaurant14时候会报错， 我在报错以后注释了laptop14 重新运行restaurant14报错信息如下：
(1) 在测试时候  Loss: nan， 在运行laptop14没有这个问题
(2)  TypeError: object of type 'NoneType' has no len()
我应该只是把bert路径改成本地的， 其他没有改
```

Remote ABSADataset version: 2022.03.22 Local ABSADatasets version: 2022.03.22
Loading Restaurant14 dataset from: https://github.com/yangheng95/ABSADatasets
FindFile Warning: multiple targets ['integrated_datasets/apc_datasets/110.SemEval/112.arts_restaurant14', 'integrated_datasets/apc_datasets/110.SemEval/114.restaurant14'] found but return the shortest path
There are augmented datasets available at integrated_datasets/apc_datasets/110.SemEval/114.restaurant14, remove .ignore to activate them.
Loading dataset cache: asgcn_bert.Restaurant14.dataset.172197abfb6ef5d6d4a92a14b04e9b57e092d8afa7107743bb39249555c3a89e.cache
Some weights of the model checkpoint at /home/hukai/PyABSA/bert were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
2022-03-28 22:32:29,900 INFO: cuda memory allocated:495774208
2022-03-28 22:32:29,900 INFO: ABSADatasetsVersion:2022.03.22	-->	Calling Count:0
2022-03-28 22:32:29,900 INFO: MV:<metric_visualizer.metric_visualizer.MetricVisualizer object at 0x7f7da271a970>	-->	Calling Count:0
2022-03-28 22:32:29,900 INFO: PyABSAVersion:1.9.0	-->	Calling Count:0
2022-03-28 22:32:29,900 INFO: TorchVersion:1.11.0+cuda11.3	-->	Calling Count:0
2022-03-28 22:32:29,900 INFO: TransformersVersion:4.17.0	-->	Calling Count:0
2022-03-28 22:32:29,900 INFO: auto_device:True	-->	Calling Count:1
2022-03-28 22:32:29,900 INFO: batch_size:16	-->	Calling Count:2
2022-03-28 22:32:29,900 INFO: cache_dataset:True	-->	Calling Count:1
2022-03-28 22:32:29,900 INFO: cross_validate_fold:-1	-->	Calling Count:0
2022-03-28 22:32:29,900 INFO: dataset_file:{'train': ['integrated_datasets/apc_datasets/110.SemEval/114.restaurant14/Restaurants_Train.xml.seg'], 'test': ['integrated_datasets/apc_datasets/110.SemEval/114.restaurant14/Restaurants_Test_Gold.xml.seg'], 'valid': []}	-->	Calling Count:0
2022-03-28 22:32:29,900 INFO: dataset_name:Restaurant14	-->	Calling Count:2
2022-03-28 22:32:29,900 INFO: deep_ensemble:False	-->	Calling Count:1
2022-03-28 22:32:29,900 INFO: device:cuda:0	-->	Calling Count:6
2022-03-28 22:32:29,900 INFO: device_name:NVIDIA GeForce RTX 3070	-->	Calling Count:0
2022-03-28 22:32:29,900 INFO: dropout:0.5	-->	Calling Count:0
2022-03-28 22:32:29,900 INFO: dynamic_truncate:True	-->	Calling Count:0
2022-03-28 22:32:29,900 INFO: embed_dim:768	-->	Calling Count:1
2022-03-28 22:32:29,900 INFO: evaluate_begin:2	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: hidden_dim:768	-->	Calling Count:6
2022-03-28 22:32:29,901 INFO: hops:3	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: index_to_label:{0: 'Negative', 1: 'Neutral', 2: 'Positive'}	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: initializer:xavier_uniform_	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: inputs_cols:['aspect_indices', 'dependency_graph', 'left_aspect_indices', 'left_dependency_graph', 'left_indices', 'left_left_indices', 'right_aspect_indices', 'right_dependency_graph', 'right_left_indices', 'text_bert_indices']	-->	Calling Count:3
2022-03-28 22:32:29,901 INFO: l2reg:0.0005	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: label_to_index:{'Negative': 0, 'Neutral': 1, 'Positive': 2}	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: learning_rate:2e-05	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: log_step:5	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: lsa:False	-->	Calling Count:3
2022-03-28 22:32:29,901 INFO: max_seq_len:100	-->	Calling Count:1
2022-03-28 22:32:29,901 INFO: model:<class 'pyabsa.core.apc.classic.__bert__.models.asgcn_bert.ASGCN_BERT'>	-->	Calling Count:5
2022-03-28 22:32:29,901 INFO: model_name:asgcn_bert	-->	Calling Count:2
2022-03-28 22:32:29,901 INFO: model_path_to_save:checkpoints	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: num_epoch:10	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: optimizer:adam	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: patience:99999	-->	Calling Count:2
2022-03-28 22:32:29,901 INFO: polarities_dim:3	-->	Calling Count:1
2022-03-28 22:32:29,901 INFO: pretrained_bert:/home/hukai/PyABSA/bert	-->	Calling Count:3
2022-03-28 22:32:29,901 INFO: save_mode:1	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: seed:1	-->	Calling Count:7
2022-03-28 22:32:29,901 INFO: show_metric:False	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: similarity_threshold:1	-->	Calling Count:0
2022-03-28 22:32:29,901 INFO: use_syntax_based_SRD:True	-->	Calling Count:0
2022-03-28 22:32:29,904 INFO: ***** Running training for Aspect Polarity Classification *****
2022-03-28 22:32:29,904 INFO: Training set examples = 3608
2022-03-28 22:32:29,904 INFO: Test set examples = 1120
2022-03-28 22:32:29,904 INFO: Total params = 123657999, Trainable params = 123657999, Non-trainable params = 0
2022-03-28 22:32:29,904 INFO: Batch size = 16
2022-03-28 22:32:29,904 INFO: Num steps = 140
100%|██████████| 226/226 [00:28<00:00,  7.97it/s, Epoch:0 | Loss: nan | No evaluation until epoch:2]
100%|██████████| 226/226 [00:29<00:00,  7.76it/s, Epoch:1 | Loss: nan | No evaluation until epoch:2]
100%|██████████| 226/226 [02:06<00:00,  1.78it/s, Epoch:2 | Loss:nan | Test Acc:17.50(max:17.50) | Test F1:9.93(max:9.93)]
100%|██████████| 226/226 [02:03<00:00,  1.84it/s, Epoch:3 | Loss:nan | Test Acc:17.50(max:17.50) | Test F1:9.93(max:9.93)]
100%|██████████| 226/226 [02:05<00:00,  1.80it/s, Epoch:4 | Loss:nan | Test Acc:17.50(max:17.50) | Test F1:9.93(max:9.93)]
100%|██████████| 226/226 [02:03<00:00,  1.83it/s, Epoch:5 | Loss:nan | Test Acc:17.50(max:17.50) | Test F1:9.93(max:9.93)]
100%|██████████| 226/226 [02:03<00:00,  1.83it/s, Epoch:6 | Loss:nan | Test Acc:17.50(max:17.50) | Test F1:9.93(max:9.93)]
100%|██████████| 226/226 [02:03<00:00,  1.83it/s, Epoch:7 | Loss:nan | Test Acc:17.50(max:17.50) | Test F1:9.93(max:9.93)]
100%|██████████| 226/226 [02:06<00:00,  1.78it/s, Epoch:8 | Loss:nan | Test Acc:17.50(max:17.50) | Test F1:9.93(max:9.93)]
100%|██████████| 226/226 [02:05<00:00,  1.80it/s, Epoch:9 | Loss:nan | Test Acc:17.50(max:17.50) | Test F1:9.93(max:9.93)]
2022-03-28 22:50:05,180 INFO:  ------------------------------------- Metric Visualizer ------------------------------------- 
╒════════════════════════════╤══════════╤════════════════════════════╤════════════════════════════════════════════════════════════╕
│ Metric                     │ Config   │ Values (First 10 values)   │ Summary                                                    │
╞════════════════════════════╪══════════╪════════════════════════════╪════════════════════════════════════════════════════════════╡
│ Max-Test-Acc w/o Valid Set │ Config-0 │ [17.5]                     │ ['Avg:17.5, Median: 17.5, IQR: 0.0, Max: 17.5, Min: 17.5'] │
├────────────────────────────┼──────────┼────────────────────────────┼────────────────────────────────────────────────────────────┤
│ Max-Test-F1 w/o Valid Set  │ Config-0 │ [9.93]                     │ ['Avg:9.93, Median: 9.93, IQR: 0.0, Max: 9.93, Min: 9.93'] │
╘════════════════════════════╧══════════╧════════════════════════════╧════════════════════════════════════════════════════════════╛
 -------------------- https://github.com/yangheng95/metric_visualizer --------------------

Training finished, we hope you can share your checkpoint with community, please see: https://github.com/yangheng95/PyABSA/blob/release/demos/documents/share-checkpoint.md
Load sentiment classifier from checkpoints/asgcn_bert_Restaurant14_acc_17.5_f1_9.93/
config: checkpoints/asgcn_bert_Restaurant14_acc_17.5_f1_9.93/asgcn_bert.config
state_dict: checkpoints/asgcn_bert_Restaurant14_acc_17.5_f1_9.93/asgcn_bert.state_dict
model: None
tokenizer: checkpoints/asgcn_bert_Restaurant14_acc_17.5_f1_9.93/asgcn_bert.tokenizer
/home/hukai/PyABSA/pyabsa/functional/trainer/trainer.py:161: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/hukai/PyABSA/demos/aspect_polarity_classification/bert-baselines/logs/asgcn_bert_20220328 223200/training.log' mode='a' encoding='utf8'>
  self.logger.removeHandler(self.logger.handlers[0])
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Some weights of the model checkpoint at /home/hukai/PyABSA/bert were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Caching dataset... please remove cached dataset if change model or dataset
Config used in Training:
ABSADatasetsVersion:2022.03.22	-->	Calling Count:0
MV:<metric_visualizer.metric_visualizer.MetricVisualizer object at 0x7f7e94a894c0>	-->	Calling Count:0
PyABSAVersion:1.9.0	-->	Calling Count:0
TorchVersion:1.11.0+cuda11.3	-->	Calling Count:0
TransformersVersion:4.17.0	-->	Calling Count:0
auto_device:True	-->	Calling Count:456
batch_size:16	-->	Calling Count:5
cache_dataset:True	-->	Calling Count:2
cross_validate_fold:-1	-->	Calling Count:2
dataset_file:{'train': ['integrated_datasets/apc_datasets/110.SemEval/114.restaurant14/Restaurants_Train.xml.seg'], 'test': ['integrated_datasets/apc_datasets/110.SemEval/114.restaurant14/Restaurants_Test_Gold.xml.seg'], 'valid': []}	-->	Calling Count:455
dataset_name:Restaurant14	-->	Calling Count:4
deep_ensemble:False	-->	Calling Count:2
device:cuda:0	-->	Calling Count:7356
device_name:NVIDIA GeForce RTX 3070	-->	Calling Count:0
dropout:0.5	-->	Calling Count:0
dynamic_truncate:True	-->	Calling Count:0
embed_dim:768	-->	Calling Count:2
ensemble_mode:cat	-->	Calling Count:0
evaluate_begin:2	-->	Calling Count:182
hidden_dim:768	-->	Calling Count:12
hops:3	-->	Calling Count:0
index_to_label:{0: 'Negative', 1: 'Neutral', 2: 'Positive'}	-->	Calling Count:0
initializer:xavier_uniform_	-->	Calling Count:1
inputs_cols:['aspect_indices', 'dependency_graph', 'left_aspect_indices', 'left_dependency_graph', 'left_indices', 'left_left_indices', 'right_aspect_indices', 'right_dependency_graph', 'right_left_indices', 'text_bert_indices']	-->	Calling Count:531
l2reg:0.0005	-->	Calling Count:1
label_to_index:{'Negative': 0, 'Neutral': 1, 'Positive': 2}	-->	Calling Count:0
learning_rate:2e-05	-->	Calling Count:1
log_step:5	-->	Calling Count:456
lsa:False	-->	Calling Count:531
max_seq_len:100	-->	Calling Count:2
max_test_metrics:{'max_apc_test_acc': 0.175, 'max_apc_test_f1': 0.09929078014184396}	-->	Calling Count:4
metrics_of_this_checkpoint:{'acc': 0.175, 'f1': 0.09929078014184396}	-->	Calling Count:2
model:<class 'pyabsa.core.apc.classic.__bert__.models.asgcn_bert.ASGCN_BERT'>	-->	Calling Count:9
model_name:asgcn_bert	-->	Calling Count:6
model_path_to_save:checkpoints	-->	Calling Count:3
num_epoch:10	-->	Calling Count:2
optimizer:adam	-->	Calling Count:1
patience:99999	-->	Calling Count:5
polarities_dim:3	-->	Calling Count:5
pretrained_bert:/home/hukai/PyABSA/bert	-->	Calling Count:5
save_mode:1	-->	Calling Count:1
seed:1	-->	Calling Count:7
show_metric:False	-->	Calling Count:0
similarity_threshold:1	-->	Calling Count:0
use_syntax_based_SRD:True	-->	Calling Count:0
Loading dataset cache: asgcn_bert.Restaurant14.dataset.82af0043974920694f0407f402b618b4bb0c01eb7d77e58e049c1c7de89ffeec.cache
Some weights of the model checkpoint at /home/hukai/PyABSA/bert were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "/home/hukai/PyABSA/demos/aspect_polarity_classification/bert-baselines/train_apc_bert_baseline.py", line 36, in <module>
    sent_classifier = APCTrainer(config=apc_config_english,
  File "/home/hukai/PyABSA/pyabsa/functional/trainer/trainer.py", line 151, in train
    model_path.append(self.train_func(self.config, self.from_checkpoint, self.logger))
  File "/home/hukai/PyABSA/pyabsa/utils/pyabsa_utils.py", line 173, in decorated
    return f(*args, **kwargs)
  File "/home/hukai/PyABSA/pyabsa/core/apc/training/apc_trainer.py", line 557, in train4apc
    trainer = Instructor(opt, logger)
  File "/home/hukai/PyABSA/pyabsa/core/apc/training/apc_trainer.py", line 42, in __init__
    self.model = APCEnsembler(self.opt)
  File "/home/hukai/PyABSA/pyabsa/core/apc/models/ensembler.py", line 142, in __init__
    train_sampler = RandomSampler(self.train_set if not self.train_set else self.train_set)
  File "/home/hukai/anaconda3/envs/DGEDT/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 96, in __init__
    if not isinstance(self.num_samples, int) or self.num_samples <= 0:
  File "/home/hukai/anaconda3/envs/DGEDT/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 104, in num_samples
    return len(self.data_source)
TypeError: object of type 'NoneType' has no len()

```
我在本地ubuntu20.04 显卡型号3070
pyabsa                    1.9.0
pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0  
numpy                     1.22.3 
networkx                  2.7.1

**Comment by yangheng95** [comment]
这是来自https://github.com/GeneZC/ASGCN 的模型，请尝试升级至V1.9.2. 
至于Rest14上的问题我无法重现，请清楚数据集缓存删除已下载数据集重试

**Comment by yangheng95** [comment]
我发现还是偶尔存在loss=nan的问题，这个需要原作者修复

**Comment by yangheng95** [comment]
I am sorry that I won't fix any model-specific problems for third-party models in the future due to limited time.
