### ISSUE TITLE
Error when running lsa_deberta_large

### ISSUE THREAD

**Issue by pepi99** [yangheng95/PyABSA#165]
I am running run_fast_lsa_deberta_large.py

Error is: 

Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/ec2-user/PyABSA/demos/aspect_polarity_classification/run_fast_lsa_deberta_large.py", line 144, in <module>
    auto_device=True  # automatic choose CUDA or CPU
  File "/home/ec2-user/PyABSA/pyabsa/functional/trainer/trainer.py", line 138, in __init__
    self.train()
  File "/home/ec2-user/PyABSA/pyabsa/functional/trainer/trainer.py", line 156, in train
    model = self.model_class(model_arg=self.train_func(self.config, self.from_checkpoint, self.logger))
  File "/home/ec2-user/PyABSA/pyabsa/utils/pyabsa_utils.py", line 173, in decorated
    return f(*args, **kwargs)
  File "/home/ec2-user/PyABSA/pyabsa/core/apc/training/apc_trainer.py", line 560, in train4apc
    return trainer.run()
  File "/home/ec2-user/PyABSA/pyabsa/core/apc/training/apc_trainer.py", line 544, in run
    return self._train(criterion)
  File "/home/ec2-user/PyABSA/pyabsa/core/apc/training/apc_trainer.py", line 141, in _train
    return self._train_and_evaluate(criterion)
  File "/home/ec2-user/PyABSA/pyabsa/core/apc/training/apc_trainer.py", line 206, in _train_and_evaluate
    loss.backward()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/home/ec2-user/.local/lib/python3.7/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 119, in backward
    inputGrad = _softmax_backward_data(grad_output, output, self.dim, output)
TypeError: _softmax_backward_data(): argument 'input_dtype' (position 4) must be torch.dtype, not Tensor

**Comment by pepi99** [comment]
Some info:
[ec2-user@... PyABSA]$ python3 --version
Python 3.7.10
[ec2-user... PyABSA]$ pip3 --version
pip 22.0.4 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

**Comment by yangheng95** [comment]
If your torch is above1.10.0，please revert to 1.10.0

**Comment by pepi99** [comment]
Okay it works now. thanks
