### ISSUE TITLE
升级到1.16.18后出现异常

### ISSUE THREAD

**Issue by yaoysyao** [yangheng95/PyABSA#227]
升级到最新版本以及将pyabsadataset使用最新版后，出现异常错误，如下：
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\work\PyFakeReview\fake_review\pyabsa_emotion.py", line 12, in <module>
    from pyabsa import ATEPCCheckpointManager
  File "D:\anconda3\lib\site-packages\pyabsa\__init__.py", line 16, in <module>
    from pyabsa.functional.trainer import APCTrainer, ATEPCTrainer, TCTrainer, TADTrainer
  File "D:\anconda3\lib\site-packages\pyabsa\functional\__init__.py", line 9, in <module>
    from pyabsa.functional.trainer import APCTrainer, ATEPCTrainer, TCTrainer, TADTrainer, Trainer
  File "D:\anconda3\lib\site-packages\pyabsa\functional\trainer\__init__.py", line 8, in <module>
    from .trainer import Trainer, APCTrainer, ATEPCTrainer, TCTrainer, TADTrainer
  File "D:\anconda3\lib\site-packages\pyabsa\functional\trainer\trainer.py", line 11, in <module>
    import findfile
ModuleNotFoundError: No module named 'findfile'

**Comment by yaoysyao** [comment]
findfile 版本1.7.9.8

**Comment by yangheng95** [comment]
我没有遇到这个问题，卸载findfile重新安装试试？

**Comment by yaoysyao** [comment]
> 我没有遇到这个问题，卸载findfile重新安装试试？

不止findfile找不到，很多都是，把conda环境重新搞了一遍可以了，可能是我环境出问题了
