### ISSUE TITLE
Can't install pyabsa

### ISSUE THREAD

**Issue by BBabuRAA** [yangheng95/PyABSA#312]
### PyABSA Version (Required)
Latest version

### Code To Reproduce (Required)
python setup.py install

### Full Console Output (Required)
Traceback (most recent call last):
  File "C:\Users\JohnDoe\PyABSA\setup.py", line 10, in <module>
    from pyabsa import __name__, __version__
  File "C:\Users\JohnDoe\PyABSA\pyabsa\__init__.py", line 13, in <module>
    from pyabsa.utils.notification_utils.notification_utils import (
  File "C:\Users\JohnDoe\PyABSA\pyabsa\utils\__init__.py", line 9, in <module>
    from pyabsa.utils.absa_utils.make_absa_dataset import make_ABSA_dataset
  File "C:\Users\JohnDoe\PyABSA\pyabsa\utils\absa_utils\make_absa_dataset.py", line 12, in <module>
    import findfile
ModuleNotFoundError: No module named 'findfile'

### Describe the bug
I followed all the instructions to install pyabsa (I have anaconda, installed pytorch (cpu and not the cuda version), however, when installing pyabsa from source, it throws the error above, saying that the module named 'findfile' cannot be found. I am working from a company laptop so I don't know if that's why I'm getting this error. I've also tried pip installing it (--trusted...etc, as I'm working from company laptop), and it throws an error after when looking at setup.py. Please let me know if you need any additional information

### Expected behavior
It's supposed to install pyabsa onto my machine

**Comment by BBabuRAA** [comment]
Edit:
I have fixed the issue by going into the pip.ini file and adding the pypi and other python files so that it won't have the SSL error (this was most likely due to machine being a company machine, thus when pip installing anything, it will always return with SSL certificate errors)
