### ISSUE TITLE
TypeError: 'NoneType' object is not iterable - Train custom dataset from english checkpoint

### ISSUE THREAD

**Issue by sorin-simu** [yangheng95/PyABSA#344]
### PyABSA Version (Required)
PyABSA: 2.3.1,Torch: 2.0.1,Transformers: 4.29.0

### ABSADataset Version (Required if you use integrated datasets)
My custom dataset

### Code To Reproduce (Required)
dataset = 'MyDataset'

trainer = ATEPC.ATEPCTrainer(
    config,
    dataset = dataset,
    from_checkpoint="english",
    auto_device = DeviceTypeOption.AUTO,
    checkpoint_save_mode=ModelSaveOption.SAVE_MODEL_STATE_DICT,
    load_aug=False
)

### Full Console Output (Required)
C:\Users\username\PycharmProjects\pythonProject\venv\Scripts\python.exe C:\Users\username\PycharmProjects\pythonProject\train.py 
No CUDA GPU found in your device
[2023-08-02 19:33:46] (2.3.1) PyABSA(2.3.1): If your code crashes on Colab, please use the GPU runtime. Then run "pip install pyabsa[dev] -U" and restart the kernel.
Or if it does not work, you can use v1.16.27

[New Feature] Aspect Sentiment Triplet Extraction since v2.1.0 (https://github.com/yangheng95/PyABSA/tree/v2/examples-v2/aspect_sentiment_triplet_extration)
[New Feature] Aspect CategoryOpinion Sentiment Quadruple Extraction since v2.2.0 (https://github.com/yangheng95/PyABSA/tree/v2/examples-v2/aspect_opinion_sentiment_category_extraction)

No CUDA GPU found in your device
[2023-08-02 19:33:51] (2.3.1) PyABSA(2.3.1): If your code crashes on Colab, please use the GPU runtime. Then run "pip install pyabsa[dev] -U" and restart the kernel.
Or if it does not work, you can use v1.16.27

[New Feature] Aspect Sentiment Triplet Extraction since v2.1.0 (https://github.com/yangheng95/PyABSA/tree/v2/examples-v2/aspect_sentiment_triplet_extration)
[New Feature] Aspect CategoryOpinion Sentiment Quadruple Extraction since v2.2.0 (https://github.com/yangheng95/PyABSA/tree/v2/examples-v2/aspect_opinion_sentiment_category_extraction)

[2023-08-02 19:33:52] (2.3.1) Datasets already exist in C:\Users\username\PycharmProjects\pythonProject\integrated_datasets, skip download
[2023-08-02 19:33:52] (2.3.1) Set Model Device: cpu
[2023-08-02 19:33:52] (2.3.1) Device Name: Unknown
2023-08-02 19:33:52,497 INFO: PyABSA version: 2.3.1
2023-08-02 19:33:52,497 INFO: Transformers version: 4.29.0
2023-08-02 19:33:52,497 INFO: Torch version: 2.0.1+cpu+cudaNone
2023-08-02 19:33:52,497 INFO: Device: Unknown
2023-08-02 19:33:52,497 INFO: MyDataset in the trainer is not a exact path, will search dataset in current working directory
FindFile Warning --> multiple targets ['Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.07486201077699661', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.0830550491809845', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.08690499514341354', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.11740821599960327', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.1491866111755371', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.1784743368625641', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.36736223101615906', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.40988689661026', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.5526915192604065', 'datasets\\atepc_datasets\\999.MyDataset', 'integrated_datasets\\atepc_datasets\\999.MyDataset'] found, only return the shortest path: <datasets\atepc_datasets\999.MyDataset>
2023-08-02 19:33:53,043 INFO: You can set load_aug=True in a trainer to augment your dataset (English only yet) and improve performance.
2023-08-02 19:33:53,045 INFO: Warning! auto_evaluate=True, however cannot find test set using for evaluating!
2023-08-02 19:33:53,045 INFO: Please DO NOT mix datasets with different sentiment labels for trainer & inference !
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
C:\Users\username\PycharmProjects\pythonProject\venv\Lib\site-packages\transformers\convert_slow_tokenizer.py:454: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
convert examples to features:  67%|██████▋   | 361/539 [00:01<00:00, 338.55it/s]C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py:268: ResourceWarning: unclosed running multiprocessing pool <multiprocessing.pool.Pool state=RUN pool_size=1>
  _warn(f"unclosed running multiprocessing pool {self!r}",
ResourceWarning: Enable tracemalloc to get the object allocation traceback
[2023-08-02 19:33:57] (2.3.1) Datasets already exist in C:\Users\username\PycharmProjects\pythonProject\integrated_datasets, skip download
[2023-08-02 19:33:57] (2.3.1) Set Model Device: cpu
[2023-08-02 19:33:57] (2.3.1) Device Name: Unknown
2023-08-02 19:33:57,306 INFO: PyABSA version: 2.3.1
2023-08-02 19:33:57,307 INFO: Transformers version: 4.29.0
2023-08-02 19:33:57,307 INFO: Torch version: 2.0.1+cpu+cudaNone
2023-08-02 19:33:57,307 INFO: Device: Unknown
2023-08-02 19:33:57,307 INFO: MyDataset in the trainer is not a exact path, will search dataset in current working directory
FindFile Warning --> multiple targets ['Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.07486201077699661', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.0830550491809845', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.08690499514341354', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.11740821599960327', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.1491866111755371', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.1784743368625641', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.36736223101615906', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.40988689661026', 'Backup\\MyDataset\\fast_lcf_atepc_custom_dataset_0.5526915192604065', 'datasets\\atepc_datasets\\999.MyDataset', 'integrated_datasets\\atepc_datasets\\999.MyDataset'] found, only return the shortest path: <datasets\atepc_datasets\999.MyDataset>
2023-08-02 19:33:57,923 INFO: You can set load_aug=True in a trainer to augment your dataset (English only yet) and improve performance.
2023-08-02 19:33:57,924 INFO: Warning! auto_evaluate=True, however cannot find test set using for evaluating!
2023-08-02 19:33:57,925 INFO: Please DO NOT mix datasets with different sentiment labels for trainer & inference !
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
C:\Users\username\PycharmProjects\pythonProject\venv\Lib\site-packages\transformers\convert_slow_tokenizer.py:454: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
convert examples to features: 100%|██████████| 539/539 [00:01<00:00, 298.68it/s]
2023-08-02 19:34:02,076 INFO: Dataset Label Details: {'Neutral': 39, 'Negative': 83, 'Positive': 417, 'Sum': 539}
C:\Users\username\PycharmProjects\pythonProject\venv\Lib\site-packages\pyabsa\tasks\AspectTermExtraction\instructor\atepc_instructor.py:85: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:248.)
  lcf_cdm_vec = torch.tensor(
Some weights of the model checkpoint at microsoft/deberta-v3-base were not used when initializing DebertaV2Model: ['mask_predictions.dense.weight', 'lm_predictions.lm_head.LayerNorm.bias', 'lm_predictions.lm_head.dense.bias', 'lm_predictions.lm_head.dense.weight', 'mask_predictions.LayerNorm.weight', 'mask_predictions.LayerNorm.bias', 'lm_predictions.lm_head.LayerNorm.weight', 'mask_predictions.classifier.bias', 'lm_predictions.lm_head.bias', 'mask_predictions.classifier.weight', 'mask_predictions.dense.bias']
- This IS expected if you are initializing DebertaV2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaV2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
2023-08-02 19:34:04,283 INFO: Save cache dataset to fast_lcf_atepc.custom_dataset.dataset.4a1d5e17074f49df45bd00ea9753c3bc96c2b4d9a9a9d88e4c35bd9f881a4941.cache
2023-08-02 19:34:04,331 INFO: ABSADatasetsVersion:None	-->	Calling Count:0
2023-08-02 19:34:04,331 INFO: IOB_label_to_index:{'B-ASP': 1, 'I-ASP': 2, 'O': 3, '[CLS]': 4, '[SEP]': 5}	-->	Calling Count:1
2023-08-02 19:34:04,331 INFO: MV:<metric_visualizer.metric_visualizer.MetricVisualizer object at 0x000002379ABF8890>	-->	Calling Count:0
2023-08-02 19:34:04,331 INFO: PyABSAVersion:2.3.1	-->	Calling Count:1
2023-08-02 19:34:04,332 INFO: SRD:3	-->	Calling Count:1078
2023-08-02 19:34:04,332 INFO: TorchVersion:2.0.1+cpu+cudaNone	-->	Calling Count:1
2023-08-02 19:34:04,332 INFO: TransformersVersion:4.29.0	-->	Calling Count:1
2023-08-02 19:34:04,332 INFO: auto_device:True	-->	Calling Count:3
2023-08-02 19:34:04,332 INFO: batch_size:16	-->	Calling Count:3
2023-08-02 19:34:04,332 INFO: cache_dataset:True	-->	Calling Count:1
2023-08-02 19:34:04,332 INFO: checkpoint_save_mode:1	-->	Calling Count:4
2023-08-02 19:34:04,332 INFO: cross_validate_fold:-1	-->	Calling Count:0
2023-08-02 19:34:04,332 INFO: dataset_file:{'train': ['datasets\\atepc_datasets\\999.MyDataset\\MyDataset.train.dat.apc.atepc'], 'test': [], 'valid': []}	-->	Calling Count:5
2023-08-02 19:34:04,332 INFO: dataset_name:custom_dataset	-->	Calling Count:3
2023-08-02 19:34:04,332 INFO: device:cpu	-->	Calling Count:3
2023-08-02 19:34:04,332 INFO: device_name:Unknown	-->	Calling Count:1
2023-08-02 19:34:04,332 INFO: dropout:0.5	-->	Calling Count:1
2023-08-02 19:34:04,332 INFO: dynamic_truncate:True	-->	Calling Count:1078
2023-08-02 19:34:04,332 INFO: embed_dim:768	-->	Calling Count:0
2023-08-02 19:34:04,332 INFO: evaluate_begin:0	-->	Calling Count:0
2023-08-02 19:34:04,332 INFO: from_checkpoint:english	-->	Calling Count:0
2023-08-02 19:34:04,333 INFO: gradient_accumulation_steps:1	-->	Calling Count:3
2023-08-02 19:34:04,333 INFO: hidden_dim:768	-->	Calling Count:6
2023-08-02 19:34:04,333 INFO: index_to_IOB_label:{1: 'B-ASP', 2: 'I-ASP', 3: 'O', 4: '[CLS]', 5: '[SEP]'}	-->	Calling Count:0
2023-08-02 19:34:04,333 INFO: index_to_label:{0: 'Negative', 1: 'Neutral', 2: 'Positive'}	-->	Calling Count:1
2023-08-02 19:34:04,333 INFO: inference_model:None	-->	Calling Count:0
2023-08-02 19:34:04,333 INFO: initializer:xavier_uniform_	-->	Calling Count:0
2023-08-02 19:34:04,333 INFO: l2reg:1e-05	-->	Calling Count:2
2023-08-02 19:34:04,333 INFO: label_list:['B-ASP', 'I-ASP', 'O', '[CLS]', '[SEP]']	-->	Calling Count:1
2023-08-02 19:34:04,333 INFO: label_to_index:{'Negative': 0, 'Neutral': 1, 'Positive': 2}	-->	Calling Count:0
2023-08-02 19:34:04,333 INFO: lcf:cdw	-->	Calling Count:0
2023-08-02 19:34:04,333 INFO: learning_rate:2e-05	-->	Calling Count:1
2023-08-02 19:34:04,333 INFO: load_aug:False	-->	Calling Count:1
2023-08-02 19:34:04,333 INFO: log_step:50	-->	Calling Count:0
2023-08-02 19:34:04,333 INFO: logger:<Logger fast_lcf_atepc (INFO)>	-->	Calling Count:8
2023-08-02 19:34:04,333 INFO: max_seq_len:80	-->	Calling Count:3774
2023-08-02 19:34:04,333 INFO: model:<class 'pyabsa.tasks.AspectTermExtraction.models.__lcf__.fast_lcf_atepc.FAST_LCF_ATEPC'>	-->	Calling Count:5
2023-08-02 19:34:04,334 INFO: model_name:fast_lcf_atepc	-->	Calling Count:541
2023-08-02 19:34:04,334 INFO: model_path_to_save:checkpoints	-->	Calling Count:2
2023-08-02 19:34:04,334 INFO: num_epoch:10	-->	Calling Count:1
2023-08-02 19:34:04,334 INFO: num_labels:6	-->	Calling Count:2
2023-08-02 19:34:04,334 INFO: optimizer:adamw	-->	Calling Count:2
2023-08-02 19:34:04,334 INFO: output_dim:3	-->	Calling Count:1
2023-08-02 19:34:04,334 INFO: overwrite_cache:False	-->	Calling Count:0
2023-08-02 19:34:04,334 INFO: path_to_save:None	-->	Calling Count:1
2023-08-02 19:34:04,334 INFO: patience:99999	-->	Calling Count:0
2023-08-02 19:34:04,334 INFO: pretrained_bert:microsoft/deberta-v3-base	-->	Calling Count:5
2023-08-02 19:34:04,334 INFO: save_mode:1	-->	Calling Count:0
2023-08-02 19:34:04,334 INFO: seed:52	-->	Calling Count:7
2023-08-02 19:34:04,334 INFO: sep_indices:2	-->	Calling Count:0
2023-08-02 19:34:04,334 INFO: show_metric:False	-->	Calling Count:0
2023-08-02 19:34:04,334 INFO: spacy_model:en_core_web_sm	-->	Calling Count:1
2023-08-02 19:34:04,335 INFO: srd_alignment:True	-->	Calling Count:0
2023-08-02 19:34:04,335 INFO: task_code:ATEPC	-->	Calling Count:1
2023-08-02 19:34:04,335 INFO: task_name:Aspect Term Extraction and Polarity Classification	-->	Calling Count:0
2023-08-02 19:34:04,335 INFO: use_amp:False	-->	Calling Count:1
2023-08-02 19:34:04,335 INFO: use_bert_spc:True	-->	Calling Count:0
2023-08-02 19:34:04,335 INFO: use_syntax_based_SRD:False	-->	Calling Count:539
2023-08-02 19:34:04,335 INFO: warmup_step:-1	-->	Calling Count:0
2023-08-02 19:34:04,335 INFO: window:lr	-->	Calling Count:0
2023-08-02 19:34:04,337 INFO: Model Architecture:
 FAST_LCF_ATEPC(
  (bert4global): DebertaV2Model(
    (embeddings): DebertaV2Embeddings(
      (word_embeddings): Embedding(128100, 768, padding_idx=0)
      (LayerNorm): LayerNorm((768,), eps=1e-07, elementwise_affine=True)
      (dropout): StableDropout()
    )
    (encoder): DebertaV2Encoder(
      (layer): ModuleList(
        (0-11): 12 x DebertaV2Layer(
          (attention): DebertaV2Attention(
            (self): DisentangledSelfAttention(
              (query_proj): Linear(in_features=768, out_features=768, bias=True)
              (key_proj): Linear(in_features=768, out_features=768, bias=True)
              (value_proj): Linear(in_features=768, out_features=768, bias=True)
              (pos_dropout): StableDropout()
              (dropout): StableDropout()
            )
            (output): DebertaV2SelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-07, elementwise_affine=True)
              (dropout): StableDropout()
            )
          )
          (intermediate): DebertaV2Intermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): DebertaV2Output(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-07, elementwise_affine=True)
            (dropout): StableDropout()
          )
        )
      )
      (rel_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-07, elementwise_affine=True)
    )
  )
  (dropout): Dropout(p=0.5, inplace=False)
  (SA1): Encoder(
    (encoder): ModuleList(
      (0): SelfAttention(
        (SA): BertSelfAttention(
          (query): Linear(in_features=768, out_features=768, bias=True)
          (key): Linear(in_features=768, out_features=768, bias=True)
          (value): Linear(in_features=768, out_features=768, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (tanh): Tanh()
  )
  (SA2): Encoder(
    (encoder): ModuleList(
      (0): SelfAttention(
        (SA): BertSelfAttention(
          (query): Linear(in_features=768, out_features=768, bias=True)
          (key): Linear(in_features=768, out_features=768, bias=True)
          (value): Linear(in_features=768, out_features=768, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (tanh): Tanh()
  )
  (linear_double): Linear(in_features=1536, out_features=768, bias=True)
  (linear_triple): Linear(in_features=2304, out_features=768, bias=True)
  (pooler): BertPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
  (dense): Linear(in_features=768, out_features=3, bias=True)
  (classifier): Linear(in_features=768, out_features=6, bias=True)
)
2023-08-02 19:34:04,337 INFO: ABSADatasetsVersion:None	-->	Calling Count:0
2023-08-02 19:34:04,338 INFO: IOB_label_to_index:{'B-ASP': 1, 'I-ASP': 2, 'O': 3, '[CLS]': 4, '[SEP]': 5}	-->	Calling Count:1
2023-08-02 19:34:04,338 INFO: MV:<metric_visualizer.metric_visualizer.MetricVisualizer object at 0x000002379ABF8890>	-->	Calling Count:0
2023-08-02 19:34:04,338 INFO: PyABSAVersion:2.3.1	-->	Calling Count:1
2023-08-02 19:34:04,338 INFO: SRD:3	-->	Calling Count:1078
2023-08-02 19:34:04,338 INFO: TorchVersion:2.0.1+cpu+cudaNone	-->	Calling Count:1
2023-08-02 19:34:04,338 INFO: TransformersVersion:4.29.0	-->	Calling Count:1
2023-08-02 19:34:04,338 INFO: auto_device:True	-->	Calling Count:4
2023-08-02 19:34:04,338 INFO: batch_size:16	-->	Calling Count:3
2023-08-02 19:34:04,338 INFO: cache_dataset:True	-->	Calling Count:1
2023-08-02 19:34:04,338 INFO: checkpoint_save_mode:1	-->	Calling Count:4
2023-08-02 19:34:04,338 INFO: cross_validate_fold:-1	-->	Calling Count:1
2023-08-02 19:34:04,338 INFO: dataset_file:{'train': ['datasets\\atepc_datasets\\999.MyDataset\\MyDataset.train.dat.apc.atepc'], 'test': [], 'valid': []}	-->	Calling Count:5
2023-08-02 19:34:04,342 INFO: dataset_name:custom_dataset	-->	Calling Count:3
2023-08-02 19:34:04,342 INFO: device:cpu	-->	Calling Count:6
2023-08-02 19:34:04,342 INFO: device_name:Unknown	-->	Calling Count:1
2023-08-02 19:34:04,342 INFO: dropout:0.5	-->	Calling Count:1
2023-08-02 19:34:04,342 INFO: dynamic_truncate:True	-->	Calling Count:1078
2023-08-02 19:34:04,342 INFO: embed_dim:768	-->	Calling Count:0
2023-08-02 19:34:04,342 INFO: evaluate_begin:0	-->	Calling Count:0
2023-08-02 19:34:04,342 INFO: from_checkpoint:english	-->	Calling Count:0
2023-08-02 19:34:04,342 INFO: gradient_accumulation_steps:1	-->	Calling Count:3
2023-08-02 19:34:04,342 INFO: hidden_dim:768	-->	Calling Count:6
2023-08-02 19:34:04,342 INFO: index_to_IOB_label:{1: 'B-ASP', 2: 'I-ASP', 3: 'O', 4: '[CLS]', 5: '[SEP]'}	-->	Calling Count:0
2023-08-02 19:34:04,342 INFO: index_to_label:{0: 'Negative', 1: 'Neutral', 2: 'Positive'}	-->	Calling Count:1
2023-08-02 19:34:04,342 INFO: inference_model:None	-->	Calling Count:0
2023-08-02 19:34:04,342 INFO: initializer:xavier_uniform_	-->	Calling Count:0
2023-08-02 19:34:04,342 INFO: l2reg:1e-05	-->	Calling Count:2
2023-08-02 19:34:04,342 INFO: label_list:['B-ASP', 'I-ASP', 'O', '[CLS]', '[SEP]']	-->	Calling Count:1
2023-08-02 19:34:04,343 INFO: label_to_index:{'Negative': 0, 'Neutral': 1, 'Positive': 2}	-->	Calling Count:0
2023-08-02 19:34:04,343 INFO: lcf:cdw	-->	Calling Count:0
2023-08-02 19:34:04,343 INFO: learning_rate:2e-05	-->	Calling Count:1
2023-08-02 19:34:04,343 INFO: load_aug:False	-->	Calling Count:1
2023-08-02 19:34:04,343 INFO: log_step:50	-->	Calling Count:0
2023-08-02 19:34:04,343 INFO: logger:<Logger fast_lcf_atepc (INFO)>	-->	Calling Count:9
2023-08-02 19:34:04,343 INFO: max_seq_len:80	-->	Calling Count:3774
2023-08-02 19:34:04,343 INFO: model:<class 'pyabsa.tasks.AspectTermExtraction.models.__lcf__.fast_lcf_atepc.FAST_LCF_ATEPC'>	-->	Calling Count:5
2023-08-02 19:34:04,343 INFO: model_name:fast_lcf_atepc	-->	Calling Count:541
2023-08-02 19:34:04,343 INFO: model_path_to_save:checkpoints	-->	Calling Count:2
2023-08-02 19:34:04,343 INFO: num_epoch:10	-->	Calling Count:1
2023-08-02 19:34:04,343 INFO: num_labels:6	-->	Calling Count:2
2023-08-02 19:34:04,343 INFO: optimizer:adamw	-->	Calling Count:2
2023-08-02 19:34:04,343 INFO: output_dim:3	-->	Calling Count:1
2023-08-02 19:34:04,343 INFO: overwrite_cache:False	-->	Calling Count:0
2023-08-02 19:34:04,343 INFO: path_to_save:None	-->	Calling Count:1
2023-08-02 19:34:04,343 INFO: patience:99999	-->	Calling Count:0
2023-08-02 19:34:04,344 INFO: pretrained_bert:microsoft/deberta-v3-base	-->	Calling Count:5
2023-08-02 19:34:04,344 INFO: save_mode:1	-->	Calling Count:0
2023-08-02 19:34:04,344 INFO: seed:52	-->	Calling Count:7
2023-08-02 19:34:04,344 INFO: sep_indices:2	-->	Calling Count:0
2023-08-02 19:34:04,344 INFO: show_metric:False	-->	Calling Count:0
2023-08-02 19:34:04,344 INFO: spacy_model:en_core_web_sm	-->	Calling Count:1
2023-08-02 19:34:04,344 INFO: srd_alignment:True	-->	Calling Count:0
2023-08-02 19:34:04,344 INFO: task_code:ATEPC	-->	Calling Count:1
2023-08-02 19:34:04,344 INFO: task_name:Aspect Term Extraction and Polarity Classification	-->	Calling Count:0
2023-08-02 19:34:04,344 INFO: tokenizer:DebertaV2TokenizerFast(name_or_path='microsoft/deberta-v3-base', vocab_size=128000, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '[CLS]', 'eos_token': '[SEP]', 'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True)	-->	Calling Count:0
2023-08-02 19:34:04,344 INFO: use_amp:False	-->	Calling Count:1
2023-08-02 19:34:04,344 INFO: use_bert_spc:True	-->	Calling Count:0
2023-08-02 19:34:04,344 INFO: use_syntax_based_SRD:False	-->	Calling Count:539
2023-08-02 19:34:04,345 INFO: warmup_step:-1	-->	Calling Count:0
2023-08-02 19:34:04,345 INFO: window:lr	-->	Calling Count:0
[2023-08-02 19:34:04] (2.3.1) Downloading checkpoint:english 
[2023-08-02 19:34:04] (2.3.1) Notice: The pretrained model are used for testing, it is recommended to train the model on your own custom datasets
[2023-08-02 19:34:04] (2.3.1) Checkpoint already downloaded, skip
2023-08-02 19:34:05,658 INFO: Checkpoint downloaded at: checkpoints\ATEPC_ENGLISH_CHECKPOINT\fast_lcf_atepc_English_cdw_apcacc_82.36_apcf1_81.89_atef1_75.43
C:\Users\username\PycharmProjects\pythonProject\venv\Lib\site-packages\pyabsa\framework\instructor_class\instructor_template.py:434: ResourceWarning: unclosed file <_io.BufferedReader name='checkpoints\\ATEPC_ENGLISH_CHECKPOINT\\fast_lcf_atepc_English_cdw_apcacc_82.36_apcf1_81.89_atef1_75.43\\fast_lcf_atepc.config'>
  config = pickle.load(open(config_path[0], "rb"))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
  0%|          | 0/34 [00:00<?, ?it/s]2023-08-02 19:34:06,370 INFO: Resume trainer from Checkpoint: checkpoints\ATEPC_ENGLISH_CHECKPOINT\fast_lcf_atepc_English_cdw_apcacc_82.36_apcf1_81.89_atef1_75.43!
2023-08-02 19:34:06,371 INFO: ***** Running training for Aspect Term Extraction and Polarity Classification *****
2023-08-02 19:34:06,371 INFO:   Num examples = 539
2023-08-02 19:34:06,371 INFO:   Batch size = 16
2023-08-02 19:34:06,371 INFO:   Num steps = 330
Epoch:  0 | Smooth Loss: 0.8689:   3%|▎         | 1/34 [00:09<05:02,  9.15s/it]
Epoch:  0 | Smooth Loss: 0.5403: 100%|██████████| 34/34 [04:45<00:00,  8.38s/it]
Epoch:  1 | Smooth Loss: 0.4312: 100%|██████████| 34/34 [04:47<00:00,  8.44s/it]
Epoch:  2 | Smooth Loss: 0.3780: 100%|██████████| 34/34 [04:56<00:00,  8.73s/it]
Epoch:  3 | Smooth Loss: 0.3344: 100%|██████████| 34/34 [04:48<00:00,  8.48s/it]
Epoch:  4 | Smooth Loss: 0.3041: 100%|██████████| 34/34 [04:45<00:00,  8.40s/it]
Epoch:  5 | Smooth Loss: 0.2831: 100%|██████████| 34/34 [04:45<00:00,  8.39s/it]
Epoch:  6 | Smooth Loss: 0.2639: 100%|██████████| 34/34 [04:38<00:00,  8.19s/it]
Epoch:  7 | Smooth Loss: 0.2490: 100%|██████████| 34/34 [04:37<00:00,  8.17s/it]
Epoch:  8 | Smooth Loss: 0.2366: 100%|██████████| 34/34 [04:47<00:00,  8.44s/it]
Epoch:  9 | Smooth Loss: 0.2267: 100%|██████████| 34/34 [04:43<00:00,  8.33s/it]
Traceback (most recent call last):
  File "C:\Users\username\PycharmProjects\pythonProject\train.py", line 13, in <module>
    trainer = ATEPC.ATEPCTrainer(
              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\PycharmProjects\pythonProject\venv\Lib\site-packages\pyabsa\tasks\AspectTermExtraction\trainer\atepc_trainer.py", line 69, in __init__
    self._run()
  File "C:\Users\username\PycharmProjects\pythonProject\venv\Lib\site-packages\pyabsa\framework\trainer_class\trainer_template.py", line 241, in _run
    model_path.append(self.training_instructor(self.config).run())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\PycharmProjects\pythonProject\venv\Lib\site-packages\pyabsa\tasks\AspectTermExtraction\instructor\atepc_instructor.py", line 794, in run
    return self._train(criterion=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\PycharmProjects\pythonProject\venv\Lib\site-packages\pyabsa\framework\instructor_class\instructor_template.py", line 372, in _train
    return self._train_and_evaluate(criterion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\PycharmProjects\pythonProject\venv\Lib\site-packages\pyabsa\tasks\AspectTermExtraction\instructor\atepc_instructor.py", line 492, in _train_and_evaluate
    apc_result, ate_result = self._evaluate_acc_f1(self.test_dataloader)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\PycharmProjects\pythonProject\venv\Lib\site-packages\pyabsa\tasks\AspectTermExtraction\instructor\atepc_instructor.py", line 604, in _evaluate_acc_f1
    for i_batch, batch in enumerate(test_dataloader):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

Process finished with exit code 1

### Describe the bug
I've created a custom atepc dataset and I want to train it from the english checkpoint. 
After Epoch 9 I get the error described in here, but I still see in the checkpoints folder the new custom dataset checkpoint (see the screenshot below). 
1. How can I fix this issue ?
2. Can I use the resulted checkpoint in this conditions for predictions ?

Thanks for your work and consideration. 

### Screenshots
![image](https://github.com/yangheng95/PyABSA/assets/11425734/ae4cf358-1e84-4041-83c1-94b9500e1a39)
![image](https://github.com/yangheng95/PyABSA/assets/11425734/6c4dcc5e-7148-4abb-85c2-d0322bb7c8ae)
![image](https://github.com/yangheng95/PyABSA/assets/11425734/9a9b5f35-c7b4-4fa3-bd84-2b49e2915992)

**Comment by yangheng95** [comment]
You need to check if you got a test set. Otherwise you can split a part of train set as test set

**Comment by sorin-simu** [comment]
I've added now the test dataset and I was able to see now also the raw metric records. So even before with that error I could use my custom checkpoint already for prediction, this error was related only to measure the performance right ?

Btw, do you have some more details about how the model train is done more in details in PyAbsa and how transformers etc libraries are use ? More than what is here I mean: https://pyabsa.readthedocs.io/en/v2/

Thank you !
