### ISSUE TITLE
Running this "Extract aspect terms and classify sentiments" sample code is wrong

### ISSUE THREAD

**Issue by libaimi3270** [yangheng95/PyABSA#358]
### PyABSA Version (Required)
```
Python Version:3.9.16
PyABSA Version:2.3.3
Torch Version:1.13.1
Transformers Version:4.33.1
```
### Code To Reproduce (Required)
```
from pyabsa import AspectTermExtraction as ATEPC, available_checkpoints

# you can view all available checkpoints by calling available_checkpoints()
checkpoint_map = available_checkpoints()

aspect_extractor = ATEPC.AspectExtractor('multilingual',
                                         auto_device=True,  # False means load model on CPU
                                         cal_perplexity=True,
                                         )

# instance inference
aspect_extractor.predict(['I love this movie, it is so great!'],
                         save_result=True,
                         print_result=True,  # print the result
                         ignore_error=True,  # ignore the error when the model cannot predict the input
                         )

inference_source = ATEPC.ATEPCDatasetList.Restaurant16
atepc_result = aspect_extractor.batch_predict(target_file=inference_source,  #
                                              save_result=True,
                                              print_result=True,  # print the result
                                              pred_sentiment=True,  # Predict the sentiment of extracted aspect terms
                                              )

print(atepc_result)
```
### Full Console Output (Required)
```
[2023-10-17 10:16:23] (2.3.3) Please specify the task code, e.g. from pyabsa import TaskCodeOption
/home/libaimi/anaconda3/envs/cuda11.7/lib/python3.9/multiprocessing/pool.py:265: ResourceWarning: unclosed running multiprocessing pool <multiprocessing.pool.Pool state=RUN pool_size=1>
  _warn(f"unclosed running multiprocessing pool {self!r}",
ResourceWarning: Enable tracemalloc to get the object allocation traceback
[2023-10-17 10:20:46] (2.3.3) Fail to download checkpoints info from huggingface space, try to download from local
Traceback (most recent call last):
  File "/home/libaimi/runmodel/PyABSA-2/test/test1.py", line 4, in <module>
    checkpoint_map = available_checkpoints()
  File "/home/libaimi/anaconda3/envs/cuda11.7/lib/python3.9/site-packages/pyabsa/framework/checkpoint_class/checkpoint_utils.py", line 102, in available_checkpoints
    with open("./checkpoints.json", "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints.json'
```
### Describe the bug
```
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints.json'
```
### Expected behavior
```
![image](https://github.com/yangheng95/PyABSA/assets/128564084/33c1d224-6a07-48ce-b594-e70c262a4099)
checkpoints.json
I've put this "checkpoints.json" file in the "checkpoint_utils.py" code sibling, but this problem is still not resolved
```
Please how can I do to solve this problem，Thank you very much！

**Comment by yangheng95** [comment]
Put the json file in the path where your main py file is.

**Comment by libaimi3270** [comment]
Thank you for your answer！

**Comment by libaimi3270** [comment]
The above problem is solved, but a new problem has arisen.
The following error message is reported：
"RuntimeError: Fail to load the model from multilingual! Please make sure the version of checkpoint and PyABSA are compatible. Try to remove he checkpoint and download again 
Exception: expected str, bytes or os.PathLike object, not NoneType "

The "checkpoints.json" file I used was copied from the example from the "examples-v2" file, and the two codes in "Quick-Start" for "Extract aspect terms and classify sentiments" and "Checkpoints.json" for "Aspect-based sentiment analysis" Where can I download it?

**Comment by jg8946** [comment]
I have been having the same issue. I am not certain of the cause.

**Comment by jg8946** [comment]
Output of the command:
checkpoint_map = available_checkpoints(task_code=TaskCodeOption.Aspect_Term_Extraction_and_Classification,
    show_ckpts=True)
![image](https://github.com/yangheng95/PyABSA/assets/56629535/508ced9f-afca-464f-941b-ce4747b4a283)

Is the id field meant to be empty?

**Comment by yangheng95** [comment]
@libaimi3270 @jg8946 Can you use the checkpoint file from https://huggingface.co/spaces/yangheng/PyABSA/blob/main/checkpoints-v2.0.json ?

**Comment by libaimi3270** [comment]
Thank you, but I tried to use the checkpoint file you said and the problem was not solved，here are the checkpoint files and error messages I downloaded：
![8696db2f9b6c0d26f3de6d326d83f28](https://github.com/yangheng95/PyABSA/assets/128564084/8664c109-9826-4c21-9d89-592107d162b5)
![305bd0663d79a0e584bae43035308d6](https://github.com/yangheng95/PyABSA/assets/128564084/ea57769f-933f-4022-9805-93d6685a2d32)
![1697729148217](https://github.com/yangheng95/PyABSA/assets/128564084/a0c102c7-742b-4b18-8a5d-4f3b1caa1b4e)

**Comment by jg8946** [comment]
Hi,

Thanks for your quick response on this matter, but the same issue reoccurs:
![image](https://github.com/yangheng95/PyABSA/assets/56629535/60b53bec-2aa0-494f-be77-6cdca5026d50)
I have placed checkpoints.json in the same directory(for the spyder environment) as my python script (pyabsa_example.py):
![image](https://github.com/yangheng95/PyABSA/assets/56629535/2f35bea6-9ebe-419d-b7c9-825e0a0cb6b3)

**Comment by jg8946** [comment]
Hi - I was able to get the examples to work, but I had to revert to an earlier version of the requests package:

pip requests=2.27.1 in the Command prompt of my environment

and then adding the following to get around an SSL issue with HuggingFace:

import os 
os.environ['CURL_CA_BUNDLE'] =''

Results:
![image](https://github.com/yangheng95/PyABSA/assets/56629535/74867753-ee16-4127-973c-9d6a03f457fa)
 Instance Inference for APC does produce a small error:
![image](https://github.com/yangheng95/PyABSA/assets/56629535/633268da-8383-4558-a67f-b5a5ad9f9072)

**Comment by yangheng95** [comment]
> Thank you, but I tried to use the checkpoint file you said and the problem was not solved，here are the checkpoint files and error messages I downloaded： ![8696db2f9b6c0d26f3de6d326d83f28](https://user-images.githubusercontent.com/128564084/276666773-8664c109-9826-4c21-9d89-592107d162b5.png) ![305bd0663d79a0e584bae43035308d6](https://user-images.githubusercontent.com/128564084/276666790-ea57769f-933f-4022-9805-93d6685a2d32.png) ![1697729148217](https://user-images.githubusercontent.com/128564084/276667432-a0c102c7-742b-4b18-8a5d-4f3b1caa1b4e.png)

Hi, I am sorry for that. I am in a busy schedule in these months so I may not fix this problem in time. Why dont you use the online loading method, as it is the recommended way to load checkpoints.

**Comment by yangheng95** [comment]
> Hi - I was able to get the examples to work, but I had to revert to an earlier version of the requests package:
> 
> pip requests=2.27.1 in the Command prompt of my environment
> 
> and then adding the following to get around an SSL issue with HuggingFace:
> 
> import os os.environ['CURL_CA_BUNDLE'] =''
> 
> Results: ![image](https://user-images.githubusercontent.com/56629535/276955756-74867753-ee16-4127-973c-9d6a03f457fa.png) Instance Inference for APC does produce a small error: ![image](https://user-images.githubusercontent.com/56629535/276956240-633268da-8383-4558-a67f-b5a5ad9f9072.png)

So do you mean the latest version of the request is not compatible with PyABSA?

**Comment by libaimi3270** [comment]
> > 谢谢，但是我尝试使用您说的检查点文件，但问题没有解决，这是我下载的检查点文件和错误消息：![8696db2f9b6c0d26f3de6d326d83f28](https://user-images.githubusercontent.com/128564084/276666773-8664c109-9826-4c21-9d89-592107d162b5.png) ![305bd0663d79a0e584bae43035308d6](https://user-images.githubusercontent.com/128564084/276666790-ea57769f-933f-4022-9805-93d6685a2d32.png) ![1697729148217](https://user-images.githubusercontent.com/128564084/276667432-a0c102c7-742b-4b18-8a5d-4f3b1caa1b4e.png)
> 
> 嗨，我很抱歉。这几个月程繁忙，所以我可能无法及时解决这个问题。为什么不使用在线加载方法，因为这是加载检查点的推荐方法。

Thanks for answering my question while busy, so how do I load checkpoints using online methods?

**Comment by yangheng95** [comment]
> > > 谢谢，但是我尝试使用您说的检查点文件，但问题没有解决，这是我下载的检查点文件和错误消息：![8696db2f9b6c0d26f3de6d326d83f28](https://user-images.githubusercontent.com/128564084/276666773-8664c109-9826-4c21-9d89-592107d162b5.png) ![305bd0663d79a0e584bae43035308d6](https://user-images.githubusercontent.com/128564084/276666790-ea57769f-933f-4022-9805-93d6685a2d32.png) ![1697729148217](https://user-images.githubusercontent.com/128564084/276667432-a0c102c7-742b-4b18-8a5d-4f3b1caa1b4e.png)
> > 
> > 
> > 嗨，我很抱歉。这几个月程繁忙，所以我可能无法及时解决这个问题。为什么不使用在线加载方法，因为这是加载检查点的推荐方法。
> 
> Thanks for answering my question while busy, so how do I load checkpoints using online methods?

e.g.: https://github.com/yangheng95/PyABSA/blob/v2/examples-v2/aspect_term_extraction/extract_aspects.py

**Comment by libaimi3270** [comment]
> > > > 谢谢，但是我尝试使用您说的检查点文件，但问题没有解决，这是我下载的检查点文件和错误消息：![8696db2f9b6c0d26f3de6d326d83f28](https://user-images.githubusercontent.com/128564084/276666773-8664c109-9826-4c21-9d89-592107d162b5.png) ![305bd0663d79a0e584bae43035308d6](https://user-images.githubusercontent.com/128564084/276666790-ea57769f-933f-4022-9805-93d6685a2d32.png) ![1697729148217](https://user-images.githubusercontent.com/128564084/276667432-a0c102c7-742b-4b18-8a5d-4f3b1caa1b4e.png)
> > > 
> > > 
> > > 嗨，我很抱歉。这几个月程繁忙，所以我可能无法及时解决这个问题。为什么不使用在线加载方法，因为这是加载检查点的推荐方法。
> > 
> > 
> > Thanks for answering my question while busy, so how do I load checkpoints using online methods?
> 
> e.g.: https://github.com/yangheng95/PyABSA/blob/v2/examples-v2/aspect_term_extraction/extract_aspects.py
Thank you so much！

**Comment by libaimi3270** [comment]
> > > > 谢谢，但是我尝试使用您说的检查点文件，但问题没有解决，这是我下载的检查点文件和错误消息：![8696db2f9b6c0d26f3de6d326d83f28](https://user-images.githubusercontent.com/128564084/276666773-8664c109-9826-4c21-9d89-592107d162b5.png) ![305bd0663d79a0e584bae43035308d6](https://user-images.githubusercontent.com/128564084/276666790-ea57769f-933f-4022-9805-93d6685a2d32.png) ![1697729148217](https://user-images.githubusercontent.com/128564084/276667432-a0c102c7-742b-4b18-8a5d-4f3b1caa1b4e.png)
> > > 
> > > 
> > > 嗨，我很抱歉。这几个月程繁忙，所以我可能无法及时解决这个问题。为什么不使用在线加载方法，因为这是加载检查点的推荐方法。
> > 
> > 
> > Thanks for answering my question while busy, so how do I load checkpoints using online methods?
> 
> e.g.: https://github.com/yangheng95/PyABSA/blob/v2/examples-v2/aspect_term_extraction/extract_aspects.py

Thank you so much！

**Comment by jg8946** [comment]
The issue I had seems to be related to HuggingFace's SSL certificate setup, not with the package itself.  Reverting to requests version 2.27.1 and including os.environ['CURL_CA_BUNDLE'] ='' was something I saw in a seperate conversation about SSLErrors connecting to HuggingFace, so I tried that and it worked.

The previous discussion is here:
https://stackoverflow.com/questions/71692354/facing-ssl-error-with-huggingface-pretrained-models

Thanks for your help with this issue
