### ISSUE TITLE
Cannot execute ATEPC modelling by using self-created custom dataset

### ISSUE THREAD

**Issue by Koukotsukan** [yangheng95/PyABSA#359]
### PyABSA Version (Required)
```
Python Version: 3.9.0
PyABSA Version: latest from pip
Torch Version: latest from pip
Transformers Version: latest from pip
Other: 

See the console output for PyABSA, Torch, Transformers Version
```
### ABSADataset Version (Required if you use integrated datasets)
```
I am using my own-built custom dataset, I deleted all files inside 100.custom dataset in the integrated datasets and replaced mine data there, instead of re-register a new dataset. (But even though I register a new dataset, the error still reproduce.

我使用的是自己创建的自定义数据集，我删除了集成数据集内100.custom dataset的所有文件，并在其中替换了我的数据，而不是重新注册一个新的数据集。(但是，即使我注册了新的数据集，错误还是会重现)
```
### Code To Reproduce (Required)
```
from pyabsa import ModelSaveOption, DeviceTypeOption
import warnings
from pyabsa import AspectTermExtraction as ATEPC
config = (
    ATEPC.ATEPCConfigManager.get_atepc_config_english()
)  # this config contains 'pretrained_bert', it is based on pretrained models
config.model = ATEPC.ATEPCModelList.FAST_LCF_ATEPC  # improved version of LCF-ATEPC

warnings.filterwarnings("ignore")

config.batch_size = 16
config.patience = 2
config.log_step = -1
config.seed = [1]
config.verbose = False  # If verbose == True, PyABSA will output the model strcture and seversal processed data examples
config.notice = (
    "This is an training example for aspect term extraction"  # for memos usage
)

trainer = ATEPC.ATEPCTrainer(
    config=config,
    dataset='100.CustomDataset',
    # dataset='118.TShirt',
    from_checkpoint="",  # if you want to resume training from our pretrained checkpoints, you can pass the checkpoint name here
    auto_device=DeviceTypeOption.AUTO,  # use cuda if available
    checkpoint_save_mode=ModelSaveOption.SAVE_MODEL_STATE_DICT,  # save state dict only instead of the whole model
    #checkpoint_save_mode=0,
    load_aug=False,  # there are some augmentation dataset for integrated datasets, you use them by setting load_aug=True to improve performance
)
```
### Full Console Output (Required)
```
"H:\UM OneDrive\OneDrive - 365.um.edu.my\OneDrive - Universiti Malaya\UM\2023_1\ABSACoding\venv\Scripts\python.exe" "H:\UM OneDrive\OneDrive - 365.um.edu.my\OneDrive - Universiti Malaya\UM\2023_1\ABSA\Coding\test.py" 
No CUDA GPU found in your device
[2023-10-23 02:10:52] (2.3.4) PyABSA(2.3.4): If your code crashes on Colab, please use the GPU runtime. Then run "pip install pyabsa[dev] -U" and restart the kernel.
Or if it does not work, you can use v1.x versions, e.g., pip install pyabsa<2.0 -U




WARNING: When you fails to load a checkpoint, e.g., Unexpected key(s),
Try to downgrade transformers<=4.29.0.




No CUDA GPU found in your device
[2023-10-23 02:11:04] (2.3.4) Set Model Device: cpu
[2023-10-23 02:11:04] (2.3.4) Device Name: Unknown
2023-10-23 02:11:04,339 INFO: PyABSA version: 2.3.4
2023-10-23 02:11:04,340 INFO: Transformers version: 4.34.0
2023-10-23 02:11:04,340 INFO: Torch version: 2.1.0+cpu+cudaNone
2023-10-23 02:11:04,340 INFO: Device: Unknown
2023-10-23 02:11:04,341 INFO: 100.CustomDataset in the trainer is not a exact path, will search dataset in current working directory
2023-10-23 02:11:08,233 INFO: You can set load_aug=True in a trainer to augment your dataset (English only yet) and improve performance.
2023-10-23 02:11:08,246 INFO: Please DO NOT mix datasets with different sentiment labels for trainer & inference !
convert examples to features: 0it [00:00, ?it/s]
2023-10-23 02:11:11,609 INFO: Dataset Label Details: {'Sum': 0} <-- THIS POINT
convert examples to features: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "H:\UM OneDrive\OneDrive - 365.um.edu.my\OneDrive - Universiti Malaya\UM\2023_1\ABSA\Coding\test.py", line 43, in <module>
    trainer = ATEPC.ATEPCTrainer(
  File "H:\UM OneDrive\OneDrive - 365.um.edu.my\OneDrive - Universiti Malaya\UM\2023_1\ABSA\Coding\venv\lib\site-packages\pyabsa\tasks\AspectTermExtraction\trainer\atepc_trainer.py", line 69, in __init__
    self._run()
  File "H:\UM OneDrive\OneDrive - 365.um.edu.my\OneDrive - Universiti Malaya\UM\2023_1\ABSA\Coding\venv\lib\site-packages\pyabsa\framework\trainer_class\trainer_template.py", line 241, in _run
    model_path.append(self.training_instructor(self.config).run())
  File "H:\UM OneDrive\OneDrive - 365.um.edu.my\OneDrive - Universiti Malaya\UM\2023_1\ABSA\Coding\venv\lib\site-packages\pyabsa\tasks\AspectTermExtraction\instructor\atepc_instructor.py", line 40, in __init__
    self._load_dataset_and_prepare_dataloader()
  File "H:\UM OneDrive\OneDrive - 365.um.edu.my\OneDrive - Universiti Malaya\UM\2023_1\ABSA\Coding\venv\lib\site-packages\pyabsa\tasks\AspectTermExtraction\instructor\atepc_instructor.py", line 216, in _load_dataset_and_prepare_dataloader
    train_sampler = RandomSampler(self.train_set)
  File "H:\UM OneDrive\OneDrive - 365.um.edu.my\OneDrive - Universiti Malaya\UM\2023_1\ABSA\Coding\venv\lib\site-packages\torch\utils\data\sampler.py", line 140, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
ValueError: num_samples should be a positive integer value, but got num_samples=0   <-- THIS POINT 
2023-10-23 02:11:12,368 INFO: Dataset Label Details: {'Sum': 0}
```
### Describe the bug
```
The dataset was built through ABSADataset Auto annotation tool, for no reason the PyABSA cannot detect any samples from the dataset.  
```
### Expected behavior
```
The model was training by own custom dataset.
模型可以通过自定义数据集进行训练。
```
### Screenshots
```
In addition to REQUIRED text information, you can add screenshots to help explain your problem.
```
This is a sample review ATEPC from the dataset. I dont know if there is any format error or something. I tried to use txt instead of csv, I tried to remove all symbols, but nothing helps(same error). May I please request you to help me find the wrong point. Thank you in advance.
这是数据集中的 ATEPC 审查样本。我不知道是否存在格式错误或其他问题。我试着用 txt 而不是 csv，我试着删除所有符号，但都无济于事（一样的报错）。请您帮我找出错误点。在此先表示感谢。

```
" O -100
I O -100
ve O -100
bought O -100
mostly O -100
everything O -100
for O -100
my O -100
business O -100
from O -100
Alibaba O -100
. O -100
Most O -100
of O -100
the O Negative
suppliers B-ASP -100
I O -100
ve O -100
dealt O -100
with O -100
have O -100
been O -100
great O -100
- O -100
I O -100
ve O -100
received B-ASP -100
what O -100
I O -100
ordered O -100
pretty O -100
quickly O -100
. O -100
Just O -100
recently O -100
, O -100
I O -100
had O -100
an O -100
order O -100
go O -100
horribly O -100
wrong O -100
when O -100
a O -100
supplier O -100
took O -100
months O -100
to O -100
even O -100
mail O -100
out O -100
my O -100
package O -100
, O -100
and O -100
then O -100
it O -100
was O -100
not O -100
what O -100
I O -100
ordered O -100
. O -100
I O -100
messaged O -100
them O -100
, O -100
and O -100
they O -100
basically O -100
told O -100
me O -100
to O -100
just O -100
deal O -100
with O -100
it O -100
and O -100
would O -100
not O -100
make O -100
it O -100
right O -100
. O -100
They O -100
said O -100
if O -100
I O -100
wanted O -100
a O -100
refund O -100
, O -100
I O -100
had O -100
to O -100
pay O -100
to O -100
ship O -100
the O -100
items O -100
that O -100
were O -100
not O -100
what O -100
I O -100
ordered O -100
back O -100
, O -100
and O -100
the O -100
shipping B-ASP -100
cost O -100
was O -100
most O -100
of O -100
what O -100
I O -100
paid O -100
. O -100
I O -100
was O -100
nervous O -100
about O -100
how O -100
Alibaba O -100
would O -100
handle O -100
it O -100
. O -100
I O -100
definitely O -100
will O -100
continue O -100
shopping O -100
here O -100
after O -100
the O -100
experience O -100
- O -100
I O -100
was O -100
issued B-ASP -100
a O -100
full O -100
refund B-ASP -100
and O -100
did O -100
not O -100
have O -100
to O -100
pay O -100
to O -100
ship O -100
what O -100
I O -100
did O -100
not O -100
order O -100
back O -100
( O -100
thank O -100
goodness O -100
) O -100
. O -100
Thank O -100
you O -100
, O -100
Alibaba O -100
. O -100
" O -100
```

**Comment by Koukotsukan** [comment]
By the way if you require the datasets to find out the problems, I am glad to pm you with the dataset. Thank you for this whole project.

**Comment by yangheng95** [comment]
如果你需要训练，那么sentiment标签都是-100是不正确的，每个aspect需要有一个sentiment标签，详情请参看现有数据

**Comment by Koukotsukan** [comment]
> 如果你需要训练，那么sentiment标签都是-100是不正确的，每个aspect需要有一个sentiment标签，详情请参看现有数据

明白，感谢回复，那可能我应该重新看一下我标注的时候的问题了。谢谢大佬。
能顺便问一下，为什么用了Auto Annotation Tool出来的Sentiment都是-100吗？

**Comment by yangheng95** [comment]
这个可能是代码的bug，我目前正在参加CIKM，预计段时间没有办法修复代码。尽量自己解决一下试试

**Comment by Koukotsukan** [comment]
> 这个可能是代码的bug，我目前正在参加CIKM，预计段时间没有办法修复代码。尽量自己解决一下试试

好的，感谢大佬，我自己去探索一下原因，Good day/night！

**Comment by Koukotsukan** [comment]
For anyone who is facing the same issue as me, I have found a solution.
Firstly, go to use the Auto Annotation Tool, after it is finished, save the 2 apc files.
Secondly, use https://github.com/yangheng95/PyABSA/blob/release/demos/aspect_term_extraction/convert_apc_set_to_atepc_set.py the script from the contributor of the project, to convert your APC to ATEPC. (The script is out of date, here are the outdated code part:
```
from pyabsa.utils.file_utils import convert_apc_set_to_atepc_set
from pyabsa.functional import ABSADatasetList
```
you can just remove something to make the script works again:
```
from pyabsa.utils import convert_apc_set_to_atepc_set
from pyabsa import ABSADatasetList
```

Then, the problem should be resolved. The FAST-LCF-BERT now can train your models based on ATEPC.


如果有人遇到和我一样的问题，我已经找到了解决办法。
首先，使用Auto Annotation工具，完成后保存 生成的2 个 apc 文件。
其次，使用 https://github.com/yangheng95/PyABSA/blob/release/demos/aspect_term_extraction/convert_apc_set_to_atepc_set.py 这个项目贡献者提供的脚本将 APC 转换为 ATEPC。(该脚本已经过时，以下是过时的代码部分：
```
from pyabsa.utils.file_utils import convert_apc_set_too_atepc_set
from pyabsa.functional import ABSADatasetList
```
您可以删除一些内容，使脚本重新运行：
```
from pyabsa.utils import convert_apc_set_too_atepc_set
from pyabsa import ABSADatasetList
```


然后，问题应该就解决了。FAST-LCF-BERT现在可以根据ATEPC训练模型了。
