### ISSUE TITLE
能否提供一个国内的下载地址下载checkpoints.json文件，Google下载不了

### ISSUE THREAD

**Issue by SmallSmallQiu** [yangheng95/PyABSA#40]
ssh://kailing@10.134.35.150:22/home/kailing/anaconda3/envs/kailing3.7/bin/python -u /home/kailing/.pycharm_helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 0.0.0.0 --port 45209 --file /home/kailing/qiu/ABSA/PyABSA-release/examples/aspect_term_extraction/extract_aspects_chinese.py
pydev debugger: process 14671 is connecting

Connected to pydev debugger (build 183.5153.39)
Downloading 1jjaAQM6F9s_IEXNpaY-bQF9EOrhq0PBD into ./checkpoints.json... Traceback (most recent call last):
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f2a0f878690>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1jjaAQM6F9s_IEXNpaY-bQF9EOrhq0PBD (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a0f878690>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kailing/.pycharm_helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/kailing/.pycharm_helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/kailing/.pycharm_helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/kailing/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/kailing/qiu/ABSA/PyABSA-release/examples/aspect_term_extraction/extract_aspects_chinese.py", line 28, in <module>
    model_path = ATEPCTrainedModelManager.get_checkpoint(checkpoint_name='Chinese')
  File "/home/kailing/qiu/ABSA/PyABSA-release/pyabsa/model_utils.py", line 98, in get_checkpoint
    atepc_checkpoint = update_checkpoints('ATEPC')
  File "/home/kailing/qiu/ABSA/PyABSA-release/pyabsa/model_utils.py", line 115, in update_checkpoints
    dest_path='./checkpoints.json')
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/google_drive_downloader/google_drive_downloader.py", line 56, in download_file_from_google_drive
    response = session.get(GoogleDriveDownloader.DOWNLOAD_URL, params={'id': file_id}, stream=True)
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/kailing/anaconda3/envs/kailing3.7/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1jjaAQM6F9s_IEXNpaY-bQF9EOrhq0PBD (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a0f878690>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
^C
Process finished with exit code 1

**Comment by yangheng95** [comment]
checkpoint.json是代码用来索引Google Drive上最新保存模型的，如果没有GDrive连接权限的话，可以手动下载百度云里面提供的一些模型，解压后根据模型存储路径加载模型。后续计划引入国内模型存储仓库和编写模型管理代码，不过目前没有发现比较合适的网盘及API。

百度网盘链接：https://pan.baidu.com/s/1oKkO7RJ6Ob9vY6flnJk3Sg 
提取码：ABSA

**Comment by SmallSmallQiu** [comment]
> ABSA

好滴，非常感谢
