### ISSUE TITLE
run with train_based_on_checkpoint.py ,download file error

### ISSUE THREAD

**Issue by htthYjh** [yangheng95/PyABSA#71]
When I run with train_based_on_checkpoint.py and try to download file of APC_ENGLISH_TRAINED_MODEL. There is no file in https://drive.google.com/drive/folders/1yiMTucHKy2hAx945lgzhvb9QeHvJrStC.
but release_note.json file download  sucessful

Please check it .
 Thank's
log:

Traceback (most recent call last):
  File "/workspace/osint_dev/py/PyABSA/pyabsa/functional/checkpoint/checkpoint_manager.py", line 277, in download_pretrained_model
    showsize=True)
  File "/workspace/osint_dev/py/PyABSA/venv/lib/python3.7/site-packages/google_drive_downloader/google_drive_downloader.py", line 76, in download_file_from_google_drive
    stream=True)
  File "/workspace/osint_dev/py/PyABSA/venv/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/workspace/osint_dev/py/PyABSA/venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/workspace/osint_dev/py/PyABSA/venv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/workspace/osint_dev/py/PyABSA/venv/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1_fwXMthAzFSctLn1qq9FoSg_8uTU_rdz&confirm=dBvX (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3c9be8a50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
python-BaseException

**Comment by yangheng95** [comment]
```
config = ATEPCConfigManager.get_atepc_config_english()

checkpoint_path = ATEPCCheckpointManager.get_checkpoint(checkpoint='english')  # or
# checkpoint_path = 'lcfs_atepc_cdw_apcacc_86.17_apcf1_58.3_atef1_70.86'

config.model = ATEPCModelList.LCFS_ATEPC
config.evaluate_begin = 4
config.num_epoch = 5

TShirt = ABSADatasetList.TShirt
aspect_extractor = Trainer(config=config,
                           dataset=TShirt,
                           from_checkpoint=checkpoint_path,
                           checkpoint_save_mode=1,
                           auto_device=True
                           )
```
![image](https://user-images.githubusercontent.com/51735130/131441011-d92e9f3c-93e3-4951-91d8-b8e7e509e740.png)
I test and found no error, have you tried another running?

**Comment by htthYjh** [comment]
Thank's ,Some error of net
